### ISSUE TITLE
version 1.7.3 not working with compose web js

### ISSUE THREAD

**Issue by sunildhiman90** [qdsfdhvh/compose-imageloader#420]
Hi im getting error in 1.7.3 in compose web (Kotlin/JS), its working fine in 1.7.1, but not in 1.7.2 and 1.7.3

Getting following error:

`Function 'CanvasBasedWindow$composable' can not be called: No function found for symbol 'androidx.compose.ui.window/CanvasBasedWindow$composable|CanvasBasedWindow$composable(kotlin.String?;kotlin.String;kotlin.coroutines.SuspendFunction0<androidx.compose.ui.unit.IntSize>?;kotlin.Boolean;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){}[0]'
IrLinkageError: Function 'CanvasBasedWindow$composable' can not be called: No function found for symbol 'androidx.compose.ui.window/CanvasBasedWindow$composable|CanvasBasedWindow$composable(kotlin.String?;kotlin.String;kotlin.coroutines.SuspendFunction0<androidx.compose.ui.unit.IntSize>?;kotlin.Boolean;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){}[0]'
    at throwLinkageError (webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:6038:11)
    at main$lambda (webpack-internal:///./kotlin/kmpappexample.js:3846:5)`

**Comment by sunildhiman90** [comment]
And sometime getting this error:

`e: java.lang.IllegalStateException: Symbol for androidx.compose.foundation/Indication.rememberUpdatedInstance$composable|-5308894476871022020[0] is unbound`

**Comment by qdsfdhvh** [comment]
This issue seems to be caused by version differences in `compose-multiplatform`. The version `compose-imageloader 1.7.2+` is using `1.6.0-dev1334`, so you may need to upgrade the `compose-multiplatform` of your project to `1.6.0+`.

**Comment by sunildhiman90** [comment]
When will u create version with stable compose multiplatform release ? Becoz if i use dev version of compose multiplatform, it will cause version differences with other dependencies as well
